name: Free Game Notifier Bot

on:
  schedule:
    - cron: '0 * * * *' # Roda a cada 1 hora
  workflow_dispatch:

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Notifier Script
        env:
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
          ONESIGNAL_REST_API_KEY: ${{ secrets.ONESIGNAL_REST_API_KEY }}
        run: node notify-bot.js

      - name: Commit & Push History
        run: |
          git config --global user.name "FGH-Bot"
          git config --global user.email "bot@freegamehunter.com"
          git add notified-ids.json || true
          git commit -m "Update notification history [skip ci]" || true
          git push || true
